In [3]:
from scipy.optimize import linprog
import numpy as np

In [6]:
# c = [vector p, v]
c = [0, 0, 0, 0, -1]

# A - minimax constraints, v must be the minimum reward
q_neg = -1*both
v_col = np.ones((4,1))
#A = np.concatenate((q_neg,v_col),1)
A = both
b = [0, 0, 0, 0]

# Aeq, vector p = 1
Aeq = [[1, 1, 1, 1, 0]]
beq = [[1]]

# bound tuples
bounds = ((0,1),(0,1),(0,1),(0,1),(0, None))

In [7]:
optimize.linprog(c)

NameError: name 'optimize' is not defined

In [22]:
Q = np.ones((4,4))

In [26]:
print(c)
print(A)
print(b)
print(Aeq)
print(beq)
print(bounds)

[0, 0, 0, 0, 1]
[[-1. -1. -1. -1.  1.]
 [-1. -1. -1. -1.  1.]
 [-1. -1. -1. -1.  1.]
 [-1. -1. -1. -1.  1.]]
[0, 0, 0, 0]
[1, 1, 1, 1, 0]
[1]
((0, 1), (0, 1), (0, 1), (0, 1), (None, None))


In [8]:
res = linprog(c, A_ub=A, b_ub=b, A_eq=Aeq, b_eq=beq, bounds=bounds, options={"disp": True})

Optimization terminated successfully.
         Current function value: -1.893617   
         Iterations: 5


In [63]:
res['x'][:4]

array([0.06382979, 0.22340426, 0.41489362, 0.29787234])

In [9]:
res

     fun: -1.8936170212765957
 message: 'Optimization terminated successfully.'
     nit: 5
   slack: array([0.        , 0.        , 0.        , 0.        , 0.93617021,
       0.77659574, 0.58510638, 0.70212766])
  status: 0
 success: True
       x: array([0.06382979, 0.22340426, 0.41489362, 0.29787234, 1.89361702])

In [50]:
both = np.array([[-1., -1., -1., -1.,  1.],
       [-1., -1., -1., -1.,  1.],
       [-1., -1., -1., -1.,  1.],
       [-1., -1., -1., -1.,  1.]])


In [56]:
both

array([[ -2.,  -1.,  -3.,  -1.,   1.],
       [ -1.,  -5.,  -1.,  -1.,   1.],
       [ -1.,  -1.,  -1.,  -4.,   1.],
       [-15.,  -1.,  -1.,  -1.,   1.]])

In [5]:
both = np.array([[-2., -1., -3., -1.,  1.],
       [-1., -5., -1., -1.,  1.],
       [-1., -1., -1., -4.,  1.],
       [-15., -1., -1., -1.,  1.]])